# Generated by Django 2.1.4 on 2018-12-31 19:42

import bitsplit.corpus.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitset',
            name='logo',
            field=models.ImageField(upload_to=bitsplit.corpus.models.utils.UploadPath._get_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(upload_to=bitsplit.corpus.models.utils.UploadPath._get_file_path),
        ),
    ]
