# Generated by Django 2.1.4 on 2018-12-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bit',
            name='bitset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bits', to='corpus.BitSet'),
            preserve_default=False,
        ),
    ]
