# Generated by Django 2.1.4 on 2019-01-07 17:30

import bitsplit.corpus.models.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20190106_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitset',
            name='slug',
        ),
        migrations.AddField(
            model_name='bit',
            name='slug',
            field=models.SlugField(default='a', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitset',
            name='name',
            field=models.CharField(default='default', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='deelf', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='slug',
            field=models.SlugField(default='sgadshadfd', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rule',
            name='slug',
            field=models.SlugField(default='sgdgsdgdsgasdg', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='slug',
            field=models.SlugField(default='sdgsdasdsgsa', max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bitset',
            name='logo',
            field=models.ImageField(upload_to=bitsplit.corpus.models.utils.UploadPath._get_file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(upload_to=bitsplit.corpus.models.utils.UploadPath._get_file_path),
        ),
    ]
