# Generated by Django 2.1.4 on 2018-12-30 18:46

import bitsplit.corpus.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_bit_bitset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bytes',
        ),
        migrations.AddField(
            model_name='bit',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bit',
            name='users_bookmarked',
            field=models.ManyToManyField(related_name='bookmarked_bits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default=1, upload_to=bitsplit.corpus.models.user.upload_user_profile),
            preserve_default=False,
        ),
    ]
